Base {
  addIndicator: [Function: bound],
  addListener: [Function: bound],
  addTalibIndicator: [Function: bound],
  addTulipIndicator: [Function: bound],
  advice: [Function: bound],
  check: [Function: bound],
  emit: [Function: bound],
  eventNames: [Function: bound],
  finish: [Function: bound],
  getMaxListeners: [Function: bound],
  init: [Function: bound],
  listenerCount: [Function: bound],
  listeners: [Function: bound],
  log: [Function: bound],
  on: [Function: bound],
  once: [Function: bound],
  prependListener: [Function: bound],
  prependOnceListener: [Function: bound],
  propogateCustomCandle: [Function: bound],
  propogateTick: [Function: bound],
  removeAllListeners: [Function: bound],
  removeListener: [Function: bound],
  setMaxListeners: [Function: bound],
  tick: [Function: bound],
  update: [Function: bound],
  age: 512,
  processedTicks: 511,
  setup: true,
  settings: { my_custom_setting: 10 },
  tradingAdvisor:
   { enabled: true,
     method: 'custom',
     candleSize: 60,
     historySize: 21 },
  requiredHistory: 0,
  priceValue: 'close',
  indicators: {},
  talibIndicators: {},
  tulipIndicators: {},
  asyncTick: false,
  candlePropsCacheSize: 1000,
  deferredTicks: [],
  candleProps:
   { open: [],
     high: [],
     low: [],
     close: [],
     volume: [],
     vwp: [],
     trades: [] },
  end: [Function],
  input: 'candle',
  currentTrend: 'short',
  _events: { advice: [Function: bound] },
  _eventsCount: 1,
  candle:
   { id: 30661,
     start: moment("2017-11-14T19:33:00.000"),
     open: 6586.7,
     high: 6587.9,
     low: 6515.4,
     close: 6557,
     vwp: 6546.964351482448,
     volume: 613.6220816199999,
     trades: 1531 },
  randomNumber: 0.21612817967232245,
  toUpdate: false,
  _prevAdvice: 'short' }
